[package]
name = "roton-iced"
version = "1.0.1"
edition = "2021"

[dependencies]
chrono = "0.4"
directories = "5.0"
display-info = "0.5.7"
iced = { version = "0.14", features = ["advanced", "image", "svg", "tokio"] }
iced_video_player = "0.6.0"
image = { version = "0.25", default-features = false, features = ["png"] }
notify-rust = "4.11"
rfd = { version = "0.15", features = ["xdg-portal"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
tray-icon = { version = "0.24", default-features = false, features = ["gtk"] }
url = "2.5.8"
