import { Button, VerticalBox } from "std-widgets.slint";
import { SettingsPage } from "recorder/settings.slint";
import { ScreenPage } from "recorder/screen.slint";
import { RecordingPage } from "recorder/recording.slint";
import { RecordingFinishedPage } from "recorder/finished.slint";

export component AppWindow inherits Window {
    width: 700px;
    height: (active-page == 0 || active-page == 3) ? 100px : (active-page == 4 ? 500px : (active-page == 1 ? (audio-mode == "Mute" ? 220px : 370px) : 210px));

    no-frame: true;

    in-out property <int> active-page: 0;
    in-out property <string> save-path: "~/Videos";
    in-out property <string> audio-mode: "Mute";
    in-out property <image> last-thumbnail;

    in-out property <string> recording-mode: "fullscreen";
    in-out property <string> recording-geometry: "";

    in-out property <bool> has-slurp: true;
    in-out property <bool> has-ffmpeg: true;

    // Audio Device Properties
    in-out property <[string]> available-monitors: ["Default Monitor"];
    in-out property <[string]> available-mics: ["Default Mic"];
    in-out property <string> selected-monitor;
    in-out property <string> selected-mic;
    
    // Pause state promoted
    in-out property <bool> is-paused: false;

    callback request-close();
    callback start-recording(string, string); // mode, geometry
    callback stop-recording();
    callback toggle-pause(); // New callback
    callback choose-folder();
    callback audio-mode-changed(string);
    callback open-folder();
    callback select-area();
    callback refresh-devices();

    if (active-page == 0): VerticalBox {
        alignment: LayoutAlignment.space-between;

        HorizontalLayout {
            spacing: 5px;
            Image {
                source: @image-url("../../assets/rotonicon.png");
                width: 25px;
                height: 25px;
            }

            Text {
                font-size: 17px;
                horizontal-alignment: TextHorizontalAlignment.left;
                vertical-alignment: TextVerticalAlignment.center;
                overflow: TextOverflow.clip;
                text: "Roton Screen Recorder";
            }
        }

        HorizontalLayout {
            vertical-stretch: 0;
            height: 42px;
            spacing: 5px;
            Button {
                horizontal-stretch: 0;
                icon: @image-url("../../assets/icons/settings.svg");
                clicked => {
                    root.active-page = 1;
                }
            }

            Button {
                horizontal-stretch: 1;
                text: root.recording-mode == "fullscreen" ? "Full Screen" : "Selected Area";
                icon: root.recording-mode == "fullscreen" ? @image-url("../../assets/icons/fullscreen.svg") : @image-url("../../assets/icons/square-dashed-mouse-pointer.svg");
                clicked => {
                    root.active-page = 2;
                }
            }

            Button {
                horizontal-stretch: 1;
                icon: @image-url("../../assets/icons/video.svg");
                text: "Record";
                clicked => {
                    root.active-page = 3;
                    root.start-recording(root.recording-mode, root.recording-geometry);
                }
            }

            Button {
                horizontal-stretch: 0;
                icon: @image-url("../../assets/icons/x.svg");
                clicked => {
                    root.request-close();
                }
            }
        }
    }

    if (active-page == 1): SettingsPage {
        save-path <=> root.save-path;
        selected-audio-mode <=> root.audio-mode;
        available-monitors: root.available-monitors;
        available-mics: root.available-mics;
        selected-monitor <=> root.selected-monitor;
        selected-mic <=> root.selected-mic;
        back => {
            root.active-page = 0;
        }
        choose-folder => {
            root.choose-folder();
        }
        audio-mode-changed(mode) => {
            root.audio-mode-changed(mode);
        }
        refresh-devices => {
            root.refresh-devices();
        }
    }

    if (active-page == 2): ScreenPage {
        has-slurp: root.has-slurp;
        back => {
            root.active-page = 0;
        }
        set-fullscreen => {
            root.recording-mode = "fullscreen";
            root.recording-geometry = "";
            root.active-page = 0;
        }
        select-area => {
            root.select-area();
        }
    }

    if (active-page == 3): RecordingPage {
        is-paused <=> root.is-paused;
        toggle-pause => {
            root.toggle-pause();
        }
        stop-recording => {
            root.stop-recording();
            root.active-page = 4;
        }
    }

    if (active-page == 4): RecordingFinishedPage {
        thumbnail <=> root.last-thumbnail;
        has-ffmpeg: root.has-ffmpeg;
        // Balik ke home
        back => {
            root.active-page = 0;
        }
        open-folder => {
            root.open-folder();
        }
    }
}
