import { VerticalBox, Button } from "std-widgets.slint";

export component RecordingFinishedPage inherits Rectangle {
    width: 700px;
    height: 500px;

    in-out property <image> thumbnail;

    callback back();
    callback open-folder();

    VerticalBox {
        alignment: LayoutAlignment.space-between;
        spacing: 5px;
        Text {
            font-size: 17px;
            horizontal-alignment: TextHorizontalAlignment.center;
            overflow: TextOverflow.clip;
            text: "Recording finished!";
        }

        Rectangle {
            width: 100%;
            height: 400px;
            background: #000000;
            border-radius: 10px;
            clip: true;

            Image {
                width: 100%;
                height: 100%;
                source: root.thumbnail;
                image-fit: contain;
            }
        }

        HorizontalLayout {
            vertical-stretch: 0;
            height: 42px;
            spacing: 5px;
            Button {
                text: "Record Another";
                icon: @image-url("../../../assets/icons/video.svg");
                clicked => {
                    root.back();
                }
            }

            Button {
                text: "Open Folder";
                icon: @image-url("../../../assets/icons/folder-symlink.svg");
                clicked => {
                    root.open-folder();
                }
            }
        }
    }
}
