import { VerticalBox, Button } from "std-widgets.slint";

export component RecordingPage inherits Rectangle {
    width: 700px;
    height: 100px;

    in-out property <bool> is-paused: false;
    callback stop-recording();
    callback toggle-pause();

    VerticalBox {
        alignment: LayoutAlignment.center;
        spacing: 15px;
        Text {
            font-size: 17px;
            horizontal-alignment: TextHorizontalAlignment.center;
            overflow: TextOverflow.clip;
            text: root.is-paused ? "Paused" : "Recording...";
        }

        HorizontalLayout {
            vertical-stretch: 0;
            height: 42px;
            spacing: 5px;
            Button {
                text: root.is-paused ? "Resume" : "Pause";
                icon: root.is-paused ? @image-url("../../../assets/icons/play.svg") : @image-url("../../../assets/icons/pause.svg");
                clicked => {
                    root.toggle-pause();
                }
            }

            Button {
                text: "Stop";
                icon: @image-url("../../../assets/icons/square.svg");
                clicked => {
                    root.stop-recording();
                }
            }
        }
    }
}
