import { Button, VerticalBox, LineEdit, ComboBox } from "std-widgets.slint";

export component ScreenPage inherits Rectangle {
    width: 700px;
    height: 210px;
    in property <bool> has-slurp: true;
    property <string> selected-audio-mode: "Mute";
    callback back();
    callback set-fullscreen();
    callback select-area();

    VerticalBox {
        alignment: LayoutAlignment.start;
        spacing: 15px;

        HorizontalLayout {
            spacing: 15px;
            Button {
                horizontal-stretch: 0;
                icon: @image-url("../../../assets/icons/arrow-left.svg");
                clicked => {
                    root.back()
                }
            }

            Text {
                horizontal-stretch: 1;
                text: "Screen Selection";
                font-size: 17px;
                horizontal-alignment: left;
                vertical-alignment: center;
            }
        }

        HorizontalLayout {
            height: 190px;
            spacing: 10px;
            VerticalLayout {
                spacing: 5px;
                Button {
                    icon: @image-url("../../../assets/icons/fullscreen.svg");
                    icon-size: 64px;
                    clicked => {
                        root.set-fullscreen();
                    }
                }

                Text {
                    text: "Fullscreen";
                    color: #e0e0e0;
                    horizontal-alignment: center;
                }
            }

            VerticalLayout {
                spacing: 5px;
                Button {
                    enabled: root.has-slurp;
                    icon: @image-url("../../../assets/icons/square-dashed-mouse-pointer.svg");
                    icon-size: 64px;
                    clicked => {
                        root.select-area();
                    }
                }

                Text {
                    text: "Select Area";
                    color: root.has-slurp ? #e0e0e0 : #ffffff60;
                    horizontal-alignment: center;
                }
            }
        }
    }
}
