import { Button, VerticalBox, LineEdit, ComboBox } from "std-widgets.slint";

export component SettingsPage inherits Rectangle {
    width: 700px;
    height: root.selected-audio-mode == "Mute" ? 220px : 370px;
    in-out property <string> selected-audio-mode: "Mute";
    in-out property <string> save-path: "~/Videos";
    in-out property <[string]> available-monitors: ["Default Monitor"];
    in-out property <[string]> available-mics: ["Default Mic"];
    in-out property <string> selected-monitor;
    in-out property <string> selected-mic;
    callback back();
    callback choose-folder();
    callback audio-mode-changed(string);
    callback refresh-devices(); // Callback to ask backend to refresh device list

    VerticalBox {
        alignment: LayoutAlignment.start;
        spacing: 15px;

        HorizontalLayout {
            spacing: 15px;
            Button {
                horizontal-stretch: 0;
                icon: @image-url("../../../assets/icons/arrow-left.svg");
                clicked => {
                    root.back()
                }
            }

            Text {
                horizontal-stretch: 1;
                text: "Settings Page";
                font-size: 17px;
                horizontal-alignment: left;
                vertical-alignment: center;
            }
        }

        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Saved Video Path";
                font-size: 15px;
            }

            HorizontalLayout {
                height: 42px;
                spacing: 10px;

                LineEdit {
                    placeholder-text: "Enter path here";
                    read-only: true;
                    text: root.save-path;
                }

                Button {
                    icon: @image-url("../../../assets/icons/folder-pen.svg");
                    clicked => {
                        root.choose-folder();
                    }
                }
            }
        }

        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Audio";
                font-size: 15px;
            }

            HorizontalLayout {
                height: 42px;
                spacing: 10px;

                Button {
                    text: "Mute";
                    icon: @image-url("../../../assets/icons/volume-x.svg");
                    opacity: root.selected-audio-mode == "Mute" ? 1.0 : 0.5;
                    clicked => {
                        root.selected-audio-mode = "Mute";
                        root.audio-mode-changed("Mute");
                    }
                }

                Button {
                    text: "Screen";
                    icon: @image-url("../../../assets/icons/monitor.svg");
                    opacity: root.selected-audio-mode == "Screen" ? 1.0 : 0.5;
                    clicked => {
                        root.selected-audio-mode = "Screen";
                        root.audio-mode-changed("Screen");
                    }
                }

                Button {
                    text: "Mic";
                    icon: @image-url("../../../assets/icons/mic.svg");
                    opacity: root.selected-audio-mode == "Mic" ? 1.0 : 0.5;
                    clicked => {
                        root.selected-audio-mode = "Mic";
                        root.audio-mode-changed("Mic");
                    }
                }

                Button {
                    text: "Both";
                    icon: @image-url("../../../assets/icons/audio-lines.svg");
                    opacity: root.selected-audio-mode == "Both" ? 1.0 : 0.5;
                    clicked => {
                        root.selected-audio-mode = "Both";
                        root.audio-mode-changed("Both");
                    }
                }
            }
        }

        VerticalLayout {
            visible: root.selected-audio-mode != "Mute";
            spacing: 5px;
            Text {
                text: "Monitor";
                font-size: 15px;
            }

            ComboBox {
                model: root.available-monitors;
                current-value: root.selected-monitor;
                selected => {
                    root.selected-monitor = self.current-value;
                }
            }
        }

        VerticalLayout {
            visible: root.selected-audio-mode != "Mute";
            spacing: 5px;
            Text {
                text: "Input Mic";
                font-size: 15px;
            }

            ComboBox {
                model: root.available-mics;
                current-value: root.selected-mic;
                selected => {
                    root.selected-mic = self.current-value;
                }
            }
        }
    }
}
