import { Button, VerticalBox } from "std-widgets.slint";
import { SettingsPage } from "settings.slint";

export component AppWindow inherits Window {
    width: active-page == 1 ? 700px : 700px;
    height: active-page == 1 ? 500px : 100px;

    no-frame: true;

    property <int> active-page: 0;

    callback request-close();

    if (active-page == 0): VerticalBox {
        alignment: LayoutAlignment.space-between;

        Text {
            font-size: 17px;
            horizontal-alignment: TextHorizontalAlignment.center;
            overflow: TextOverflow.clip;
            text: "roton";
        }

        HorizontalLayout {
            vertical-stretch: 0;
            height: 42px;
            spacing: 5px;
            Button {
                horizontal-stretch: 0;
                icon: @image-url("icons/settings.svg");
                clicked => {
                    root.active-page = 1;
                }
            }

            Button {
                horizontal-stretch: 1;
                text: "Screen";
                icon: @image-url("icons/monitor.svg");
            }

            Button {
                horizontal-stretch: 1;
                text: "Record";
                icon: @image-url("icons/video.svg");
            }

            Button {
                horizontal-stretch: 0;
                icon: @image-url("icons/x.svg");
                clicked => {
                    root.request-close();
                }
            }
        }
    }

    if (active-page == 1): SettingsPage {
        back => {
            root.active-page = 0;
        }
    }
}
